const HomePageActionTypes = {
    FETCH_SECTION_DATA_START:'FETCH_SECTION_DATA_START',
    FETCH_SECTION_DATA_SUCCESS:'FETCH_SECTION_DATA_SUCCESS',
    FETCH_SECTION_DATA_FAILURE:'FETCH_SECTION_DATA_FAILURE',
    TOGGLE_IS_LOADING_TRUE:'TOGGLE_IS_LOADING_TRUE',
    TOGGLE_IS_LOADING_FALSE:'TOGGLE_IS_LOADING_FALSE',
    FETCH_COUNTRIES_START:'FETCH_COUNTRIES_START',
    FETCH_COUNTRIES_SUCCESS:'FETCH_COUNTRIES_SUCCESS',
    FETCH_COUNTRIES_FAILURE:'FETCH_COUNTRIES_FAILURE',
    SET_REGiON:'SET_REGION'
}

export default HomePageActionTypes;